package schemas

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
	"time"
)

// Movies represents a movie document in MongoDB
type Booking struct {
	ID          primitive.ObjectID `bson:"_id,omitempty"`  // MongoDB's ObjectID
	Theater   string             `bson:"theater"`      // Name of the movie
	SelectedSeats []string             `bson:"selectedSeats"`    // Description of the movie
	Time    string            `bson:"time"`       // Language of the movie
	PaymentId  string             `bson:"paymentId"`
	Date     string             `bson:"date"`        // Revenue generated by the movie
	User		string				`bson:"user"`
	Price     string			`bson:"price"`
	Movie     string			`bson:"movie"`
	 CreatedAt      time.Time          `bson:"createdAt"`
	
}

