package schemas

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Movies represents a movie document in MongoDB
type Movie struct {
	ID          primitive.ObjectID `bson:"_id,omitempty"`  // MongoDB's ObjectID
	MovieName   string             `bson:"movieName"`      // Name of the movie
	Description string             `bson:"description"`    // Description of the movie
	Language    string             `bson:"language"`       // Language of the movie
	ReleaseDate primitive.DateTime `bson:"releaseDate"`    // Release date of the movie
	Revenue     string             `bson:"revenue"`        // Revenue generated by the movie
	Genre		string				`bson:"genre"`
	Image 		string 				`bson:"image"`
	TrailerId   string				`bson:"trailerId"`
}
