package schemas

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
	"time"
)

// Movies represents a movie document in MongoDB
type Reservation struct {
	ID          primitive.ObjectID `bson:"_id,omitempty"`  // MongoDB's ObjectID
	Theater   string             `bson:"theater"`      // Name of the movie
	SelectedSeats []string             `bson:"selectedSeats"`    // Description of the movie
	Time    time.Time              `bson:"time"`       // Language of the movie
	
	Date     string             `bson:"date"`        // Revenue generated by the movie
	User		string				`bson:"user"`
	Price     string			`bson:"price"`
	 CreatedAt      time.Time          `bson:"createdAt"`
	
}

